---
name: Build and Push Golang Image to AWS ECR
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: "826953734118.dkr.ecr.ap-south-1.amazonaws.com/ecr-demo"
        ECR_REPOSITORY: "ecr-demo"
        IMAGE_TAG: "latest"
      run: |
        docker build -t 826953734118.dkr.ecr.ap-south-1.amazonaws.com/ecr-demo .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG